services:
  frontend:
    build: ./frontend
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore: 
            - ./frontend/node_modules/
        - action: rebuild
          path: ./frontend/package.json
  proxy:
    build: ./proxy
    ports:
      - "8080:80"
    depends_on:
      - backend
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "somepass"
    volumes:
      - todoapp-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "40000:40000"
    environment:
      DB_PASS: "somepass"
      DB_HOST: "database"
  migrate:
    image: migrate/migrate
    volumes:
      - type: bind
        source: ./backend/database/migrations
        target: /migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:somepass@database:5432/postgres?sslmode=disable", "up" ]
    depends_on:
      database:
        condition: service_healthy

volumes:
  todoapp-data:

