CREATE TABLE IF NOT EXISTS tasklists
(
    id   bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tasks
(
    id     BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name   VARCHAR(255),
    completed BOOLEAN DEFAULT FALSE,
    listId BIGINT REFERENCES tasklists (id) ON DELETE CASCADE
);