---
- hosts: all
  become: true
  vars:
    bin_location: /usr/local/bin/todoapi

  tasks:
    - name: Upload binary to destination
      ansible.builtin.copy:
        src: ../build/todoapibin
        dest: "{{ bin_location }}"
        mode: '0755'

    - name: Upload unit file
      ansible.builtin.template:
        src: templates/todoapi.service.j2
        dest: /etc/systemd/system/todoapi.service
#        validate: systemd-analyze verify %s
      notify: enable_todoapi_unit

  handlers:
    - name: enable_todoapi_unit
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        name: todoapi




